# Generated by Django 3.1 on 2020-08-28 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='detailphoto1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='detail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='detailphoto2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='detail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='detailphoto3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='detail'),
            preserve_default=False,
        ),
    ]
